syntax = "proto3";
package cosmos.tx.v1beta1;

service Service {
  rpc BroadcastTx(BroadcastTxRequest) returns (BroadcastTxResponse);
}

enum BroadcastMode {
  BROADCAST_MODE_UNSPECIFIED = 0;
  BROADCAST_MODE_BLOCK = 1;
  BROADCAST_MODE_SYNC = 2;
  BROADCAST_MODE_ASYNC = 3;
}

message BroadcastTxRequest {
  bytes tx_bytes = 1;
  BroadcastMode mode = 2;
}

message BroadcastTxResponse {
  TxResponse tx_response = 1;
}

message TxResponse {
  int64 height = 1;
  string txhash = 2;
  string codespace = 3;
  uint32 code = 4;
  string data = 5;
  string raw_log = 6;
  repeated ABCIMessageLog logs = 7;
  string info = 8;
  int64 gas_wanted = 9;
  int64 gas_used = 10;
  // google.protobuf.Any tx = 11;
  string timestamp = 12;
}

message ABCIMessageLog {
  uint32 msg_index = 1;
  string log = 2;
  repeated StringEvent events = 3;
}

message StringEvent {
  string type = 1;
  repeated Attribute attributes = 2;
}

message Attribute {
  string key = 1;
  string value = 2;
}
